In [30]:
import numpy as np
from numpy.linalg import norm, inv 

### Vetores


In [31]:
u = np.array([3, 2])
v = np.array([1, -1])

print(f'u + v =  {u + v}') # soma
print()
print(f'2v =  {2*v}') # mult de escalar
print()
print(f'u . v =  {u.dot(v)}') # ou pode ser u@v => produto escalar
print()
print(f'||v|| =  {norm(v)}') # módulo
print()
u = (1/norm(v)) * v
print(f'||u|| =  {norm(u):.7f}') # vetor unitário
print()

u + v =  [4 1]

2v =  [ 2 -2]

u . v =  1

||v|| =  1.4142135623730951

||u|| =  1.0000000



### Matrizes

In [32]:
Z = np.zeros([3, 3])
print(f'Matriz Nula \n={Z}')
print()
I = np.identity(3)
print(f'Matriz Identidade \n={I}')
print()
A = np.array([[1, 4, 8],
     [2, -1, 3],
     [-2, 5, 3]])
B = np.array([[4, 7, 1], 
     [3, 2, -4],
     [6, 4, -3]])
print('A + B =') # soma
print(A+B)
print()
print('2A =') # multi pelo escalar
print(2*A)
print()
print('A * B =') # multi de mattrizes
print(A@B)
print()


Matriz Nula 
=[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Matriz Identidade 
=[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

A + B =
[[ 5 11  9]
 [ 5  1 -1]
 [ 4  9  0]]

2A =
[[ 2  8 16]
 [ 4 -2  6]
 [-4 10  6]]

A * B =
[[ 64  47 -39]
 [ 23  24  -3]
 [ 25   8 -31]]



In [33]:
F = np.array([[6, 3, 10], 
              [4, 8, 5]])

P = np.array([[0.10, 0.15],
             [0.4, 0.3], 
             [0.1, 0.2]])

print("Frutas: ")
print(F)
print()
print('Preços: ')
print(P)
print()
print("Total: ")
print(F@P)

Frutas: 
[[ 6  3 10]
 [ 4  8  5]]

Preços: 
[[0.1  0.15]
 [0.4  0.3 ]
 [0.1  0.2 ]]

Total: 
[[2.8 3.8]
 [4.1 4. ]]


### Matriz de Hilbert

In [34]:
H = np.array([[1/ (i + j - 1)
            for j in range(1, 6)]
                for i in range(1, 6)])
print('H: ')
print(H)
print()
print('H inv: ')
print(inv(H))
print()
print('H @ inv H: ')
print(H@inv(H))
print()
print('inv(inv(H)): ')
print(inv(inv(H)))
print()

H: 
[[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]]

H inv: 
[[ 2.500e+01 -3.000e+02  1.050e+03 -1.400e+03  6.300e+02]
 [-3.000e+02  4.800e+03 -1.890e+04  2.688e+04 -1.260e+04]
 [ 1.050e+03 -1.890e+04  7.938e+04 -1.176e+05  5.670e+04]
 [-1.400e+03  2.688e+04 -1.176e+05  1.792e+05 -8.820e+04]
 [ 6.300e+02 -1.260e+04  5.670e+04 -8.820e+04  4.410e+04]]

H @ inv H: 
[[ 1.00000000e+00  4.05808720e-13 -9.80993065e-14  4.75974815e-13
  -2.37987408e-13]
 [-1.53025740e-14  1.00000000e+00 -1.73723998e-12 -2.82196488e-12
   1.98322840e-13]
 [ 3.12448480e-15 -6.24896960e-14  1.00000000e+00 -5.99837640e-13
   4.29846634e-13]
 [ 0.00000000e+00  2.27373675e-13 -9.09494702e-13  1.00000000e+00
   0.00000000e+00]
 [ 8.74609027e-15  2.71881283e-14 -1.15815999e-12 -6